- .github/workflows/npmpublish.yml
- package-lock.json
- package.json
> v1.0.0: feat() initial public release for gate.io nodejs SDK

- package-lock.json
- package.json
> fix(): repo url

- README.md
- package-lock.json
- package.json
> chore(): fix logo

- README.md
- package-lock.json
- package.json
> chore(): fix dynamic logo

- README.md
- package-lock.json
- package.json
> chore(): update logo

- .gitignore
- package.json
- src/RestClient.ts
> fix(): Removed Response wrapper

- examples/spot/getCandles.ts
- package.json
- src/RestClient.ts
> fix(): fixed getSpotCandles, added example, bumped version

- package-lock.json
- package.json
- src/RestClient.ts
> v1.0.8: fix() withdraw params in body

- package.json
- src/RestClient.ts
- src/types/request/rebate.ts
- src/types/response/futures.ts
- src/types/response/rebate.ts
- src/types/response/spot.ts
- src/types/response/unified.ts
Updating per release notes until 15th September, 2024
> feat(): add convert small, get margin tier, get/set GT deduction and partner endpoints

- examples/full-example.ts
- examples/futures-balance-trade.ts
Added full from zero to hero example
> feat(): Added more complex example

- docs/endpointFunctionList.md
- package-lock.json
- package.json
- src/RestClient.ts
- src/types/request/options.ts
- src/types/request/unified.ts
- src/types/response/options.ts
- src/types/response/withdrawal.ts
v1.0.16 feat():
Added new endpoints
Updated types
Updated endpoint map
> v1.0.16 feat(): Added new endpoints, updated types, updated endpoint map

- docs/endpointFunctionList.md
- package-lock.json
- package.json
- src/RestClient.ts
- src/types/request/futures.ts
- src/types/response/futures.ts
- src/types/response/wallet.ts
> v1.0.17: feat(): Added endpoints, updated types

- package-lock.json
- package.json
> v1.0.18: chore() bump dependencies, trigger release with updated token

- docs/endpointFunctionList.md
- examples/apidoc/RestClient/batchCancelFuturesOrders.js
- examples/apidoc/RestClient/getMultiLoanCurrentRates.js
- examples/apidoc/RestClient/getUserCurrencyLeverageConfig.js
- examples/apidoc/RestClient/getUserCurrencyLeverageSettings.js
- examples/apidoc/RestClient/updateUserCurrencyLeverage.js
- package-lock.json
- package.json
- src/RestClient.ts
- src/types/response/futures.ts
- src/types/response/spot.ts
- src/types/response/unified.ts
- added 4 new endpoints(Unified leverage, loan)
- updated request and response parameters
> v.1.0.22 feat(): new endpoints, updated types

- docs/endpointFunctionList.md
- examples/apidoc/RestClient/batchCancelFuturesOrders.js
- package-lock.json
- package.json
- src/RestClient.ts
- src/types/request/futures.ts
- src/types/request/spot.ts
- src/types/response/delivery.ts
- src/types/response/futures.ts
- src/types/response/wallet.ts
Made the option to insert headers directly into the parameters where it is possible. 
x-gate-exptime
> v1.1.1 feat(): updated support for headers in params directly

- docs/endpointFunctionList.md
- examples/apidoc/RestClient/getLendingAnnualizedTrendChart.js
- examples/apidoc/RestClient/updateFuturesPositionMode.js
- package-lock.json
- package.json
- src/RestClient.ts
- src/types/request/spot.ts
feat(v1.1.8): added new endpoints for position mode and annualizes lending graph
> feat(v1.1.8): added new endpoints for position mode and annualizes lending graph

- docs/endpointFunctionList.md
- package-lock.json
- package.json
- src/RestClient.ts
- src/types/response/spot.ts
> feat(v1.1.11): added params, marked deprecated

- README.md
- docs/endpointFunctionList.md
> chore(): updated readme, added endpoint map for wsclient 

- .gitignore
- README.md
- llms.txt
- package-lock.json
- package.json
- tsconfig.json
> chore(v1.2.4): add llms.txt, update tsconfig, bump dependencies, update readme

- docs/endpointFunctionList.md
- examples/apidoc/RestClient/getRiskLimitTable.js
- examples/apidoc/RestClient/setCollateralCurrency.js
- llms.txt
- package-lock.json
- package.json
- src/RestClient.ts
- src/types/request/futures.ts
- src/types/response/delivery.ts
- src/types/response/futures.ts
> feat(v1.2.6): added new endpoints and expanded types

- package-lock.json
- package.json
> chore(): bump version to 1.2.8 in package.json and package-lock.json

- docs/endpointFunctionList.md
- examples/apidoc/RestClient/getFuturesInsuranceHistory.js
- examples/apidoc/RestClient/getFuturesPositionCloseHistory.js
- examples/apidoc/RestClient/submitUnifiedLoanRepay.js
- llms.txt
- package-lock.json
- package.json
- src/RestClient.ts
- src/types/request/futures.ts
- src/types/request/spot.ts
- src/types/request/unified.ts
- src/types/request/wallet.ts
- src/types/response/futures.ts
- src/types/response/spot.ts
- src/types/response/unified.ts
> feat(v1.2.10): add new futures endpoints and update request/response types
